name=input("Enter your name:")
mobile=int(input("Enter your mobile number:"))
age=int(input("Enter your age:"))
print("Name=",name)
print("Mobile=",mobile)
print("Age=",age)
print(type(name),type(mobile),type(age))